__title__ = 'hass-nest-web'
__description__ = 'Home Assistant Integration For Nest Thermostats'
__url__ = 'https://github.com/dskrypa/hass-nest-web'
__version__ = '2023.09.11-1'
__author__ = 'Doug Skrypa'
__author_email__ = 'dskrypa@gmail.com'
__copyright__ = 'Copyright 2023 Doug Skrypa'
